Fix error when setting outplanting levels due to latest RME expecting density as vector
open-AIMS/ReefModEngine.jl pull request #29
Opened 2024-12-06 05:39 UTC by Rosejoycrocker

Resolves #28

2024-12-06 06:39 UTC, ConnectedSystems requested changes

2024-12-06 06:39 UTC, ConnectedSystems commented on src/deployment.jl
> +end
I have an issue with the function name in that it doesn't perform a "check".

To me, it should be `rme_version()` or similar as it simply returns the version number (albeit separated).
Simply `version_check` can be confusing. It's unclear at first glance: What does it mean? Version of the Julia package?

I'm also hesitant to accept it returning a vector of integers. Version numbers should be treated as IDs firstly.

I also dislike how this is being used. Remember that if you're hardcoding index values, then it's usually a smell telling you there's a better way.

In this case, I would prefer:

1. a named tuple be returned: `(major=1, minor=0, patch=28)` (following [SemVer](https://semver.org/))
2. the function name be changed to `rme_version_info()`

2024-12-06 06:39 UTC, ConnectedSystems commented on src/deployment.jl
>  coral deployment density to maintain the set grid size.
No indent for main text in docstrings

2024-12-06 06:39 UTC, ConnectedSystems commented on src/deployment.jl
> +    mod_density = (n_corals * 0.5) ./ (req_area ./ m2_TO_km2)
Is this line a duplication of `area_needed()`?

2024-12-06 06:39 UTC, ConnectedSystems commented on src/deployment.jl
> +    deployment_area_pct = min((sum(req_area) / sum(target_areas)) * 100.0, 100.0)
Calculate `sum(req_area)` once beforehand and replace the repeated `sum()` here and below please.

2024-12-06 06:39 UTC, ConnectedSystems commented on src/deployment.jl
> +    density = (version_vec[3] <= 28) && (version_vec[1] == 1) ? density : fill(density, 6)
Ignoring the hardcoded indexing here, think about what would happen if the RME version advances to v1.2.28

2024-12-06 06:39 UTC, ConnectedSystems commented on src/deployment.jl
> +    density::Vector{Float64}
Doesn't this break backward compatibility?

2024-12-06 06:39 UTC, ConnectedSystems commented on docs/src/getting_started.md
> -
Could you clarify why the outplanting removed in the example?

The commit message for this change just says "fix docs"?

2024-12-09 01:52 UTC, Rosejoycrocker commented
I believe I've addressed your comments @ConnectedSystems

2024-12-09 23:45 UTC, ConnectedSystems commented on docs/src/getting_started.md
> -
Are we dropping backward compatibility?

2024-12-09 23:47 UTC, ConnectedSystems commented on src/deployment.jl
> +    rme_ver = parse.(Int64, split(rme_ver, '.'))
No change required here, just nothing this is type unstable (going from string to vector of ints).

2024-12-09 23:48 UTC, ConnectedSystems commented on src/deployment.jl
> +- `density` : Stocking density per m². In RME versions higher than 1.0.28 density needs to be a vector
```suggestion
- `density` : Stocking density per m². In RME versions higher than v1.0.28, density is expected to be a vector, witha value for each functional group represented.
```

2024-12-09 23:49 UTC, ConnectedSystems commented on src/deployment.jl
> +    with each element representing density per species
```suggestion
- `density` : Stocking density per m². In RME versions higher than v1.0.28, density is expected to be a vector
    with each element representing the density per functional group
```

2024-12-09 23:51 UTC, ConnectedSystems commented on src/deployment.jl
> +    if !((rme_version.patch <= 28) && (rme_version.minor == 0) && (rme_version.major == 1))
Reorder to be in logical order please: major, minor, patch.

2024-12-10 03:08 UTC, Rosejoycrocker commented
I've addressed your comments @ConnectedSystems, let me know if there are others

2024-12-10 06:35 UTC, ConnectedSystems commented
@Rosejoycrocker there's still the question of what to do with the example currently in the docs.

It would be best to show how to do intervention runs with the most recent RME we have.

2024-12-11 23:08 UTC, Rosejoycrocker commented
> @Rosejoycrocker there's still the question of what to do with the example currently in the docs.
> 
> It would be best to show how to do intervention runs with the most recent version of RME we have at the very least, with a note on how to do it with older versions.

I'll add the removed example as a comment with a note about the version

2024-12-12 04:24 UTC, ConnectedSystems commented on docs/src/getting_started.md
> +
You need to demonstrate what to do with versions > v1.0.31

From the docs and matlab files it looks like they added an `rme_iv_set_outplant_heat_tolerance` function.

The relevant RME functions are:

`ivSetOutplantHeatToleranceMeanDhw` and `ivSetOutplantHeatToleranceSdDhw`

Both of which expect a vector of values for each functional group.

---

Actually, this back and forth has gone for too long. I'm going to accept and merge this as is and address the above later.

2024-12-12 04:24 UTC, ConnectedSystems approved these changes

2024-12-12 04:24 UTC, merged